[package]
name = "dodopow"
version = "0.1.0"
authors = ["Nikita Podvirnyi <krypt0nn@vk.com>"]
license = "MIT"
edition = "2024"

[dependencies]
rand_core = "0.9"

[dev-dependencies]
rand_chacha = "0.9"
